# Generated by Django 5.2.8 on 2025-11-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Customer rating out of five', max_digits=2),
        ),
    ]
