"""
Script to populate the database with sample musical instruments
Run this with: python populate_db.py
"""

import os
import django

# Setup Django environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "daves_music_store.settings")
django.setup()

from store.models import Category, Instrument


def populate_database():
    print("Starting database population...")

    # Create Categories
    categories_data = [
        {"name": "Guitars", "slug": "guitars", "description": "Acoustic and electric guitars"},
        {"name": "Bass Guitars", "slug": "bass-guitars", "description": "Electric and acoustic bass guitars"},
        {"name": "Drums", "slug": "drums", "description": "Drum kits and percussion"},
        {"name": "Keyboards", "slug": "keyboards", "description": "Pianos, synthesizers, and keyboards"},
        {"name": "Wind Instruments", "slug": "wind-instruments", "description": "Saxophones, trumpets, flutes"},
        {"name": "String Instruments", "slug": "string-instruments", "description": "Violins, cellos, and violas"},
    ]

    categories = {}
    for cat_data in categories_data:
        category, created = Category.objects.get_or_create(**cat_data)
        categories[cat_data["slug"]] = category
        print(f"{'Created' if created else 'Found'} category: {category.name}")

    # Create Instruments
    instruments_data = [
        {
            "name": "Stratocaster Electric Guitar",
            "slug": "fender-stratocaster",
            "category": categories["guitars"],
            "brand": "Fender",
            "condition": "new",
            "price": 1499.99,
            "rating": 4.8,
            "description": "Classic Fender Stratocaster with maple neck, alder body, and three single-coil pickups. Perfect for rock, blues, and pop.",
            "specifications": "- Body: Alder\n- Neck: Maple\n- Fretboard: Rosewood\n- Pickups: 3 Single-Coil\n- Bridge: Tremolo",
            "in_stock": True,
            "featured": True,
        },
        {
            "name": "Les Paul Standard",
            "slug": "gibson-les-paul",
            "category": categories["guitars"],
            "brand": "Gibson",
            "condition": "used_excellent",
            "price": 2299.99,
            "rating": 4.9,
            "description": "Iconic Gibson Les Paul with mahogany body and neck, rosewood fretboard. Incredible tone and sustain.",
            "specifications": "- Body: Mahogany\n- Top: Maple\n- Neck: Mahogany\n- Pickups: 2 Humbuckers\n- Finish: Sunburst",
            "in_stock": True,
            "featured": True,
        },
        {
            "name": "Custom 24 Electric Guitar",
            "slug": "prs-custom-24",
            "category": categories["guitars"],
            "brand": "PRS",
            "condition": "new",
            "price": 3499.99,
            "rating": 4.8,
            "description": "PRS Custom 24 with flame maple top, versatile switching system, and signature bird inlays.",
            "specifications": "- Top: Flame Maple\n- Back: Mahogany\n- Pickups: 85/15 Humbuckers\n- Switching: 5-way blade\n- Inlays: Birds",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "ES-335 Semi-Hollow",
            "slug": "gibson-es-335",
            "category": categories["guitars"],
            "brand": "Gibson",
            "condition": "used_good",
            "price": 2599.99,
            "rating": 4.7,
            "description": "Vintage-inspired Gibson ES-335 with semi-hollow construction for warm, articulate tones.",
            "specifications": "- Body: Maple/Poplar/Maple\n- Center Block: Maple\n- Pickups: Calibrated T-Type Humbuckers\n- Hardware: Nickel\n- Case: Hard shell",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Precision Bass",
            "slug": "fender-precision-bass",
            "category": categories["bass-guitars"],
            "brand": "Fender",
            "condition": "new",
            "price": 1299.99,
            "rating": 4.7,
            "description": "The legendary Fender Precision Bass. Deep, punchy tone perfect for any genre.",
            "specifications": '- Body: Alder\n- Neck: Maple\n- Scale: 34"\n- Pickups: Split Single-Coil\n- Controls: Volume, Tone',
            "in_stock": True,
            "featured": True,
        },
        {
            "name": "Jazz Bass",
            "slug": "fender-jazz-bass",
            "category": categories["bass-guitars"],
            "brand": "Fender",
            "condition": "used_good",
            "price": 899.99,
            "rating": 4.5,
            "description": "Versatile Fender Jazz Bass with bright, articulate tone. Great for funk, jazz, and rock.",
            "specifications": "- Body: Alder\n- Neck: Maple\n- Pickups: 2 Single-Coil\n- Controls: 2 Volume, 1 Tone",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "StingRay Special Bass",
            "slug": "music-man-stingray-special",
            "category": categories["bass-guitars"],
            "brand": "Ernie Ball Music Man",
            "condition": "new",
            "price": 2199.99,
            "rating": 4.8,
            "description": "Modern StingRay Special with roasted maple neck and redesigned lightweight hardware.",
            "specifications": "- Body: Select Hardwood\n- Neck: Roasted Maple\n- Pickups: Neodymium Humbucker\n- Electronics: 18v 3-Band EQ\n- Hardware: Lightweight",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "SR500E Electric Bass",
            "slug": "ibanez-sr500e",
            "category": categories["bass-guitars"],
            "brand": "Ibanez",
            "condition": "used_excellent",
            "price": 749.99,
            "rating": 4.6,
            "description": "Ibanez SR500E with sleek ergonomics, Bartolini pickups, and fast-playing neck.",
            "specifications": '- Body: Okoume\n- Neck: 5pc Jatoba/Walnut\n- Pickups: Bartolini BH2\n- Electronics: 3-band EQ\n- Scale: 34"',
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "4003 Electric Bass",
            "slug": "rickenbacker-4003",
            "category": categories["bass-guitars"],
            "brand": "Rickenbacker",
            "condition": "used_good",
            "price": 1999.99,
            "rating": 4.7,
            "description": "Classic Rickenbacker 4003 with signature piano-like tone and stereo outputs.",
            "specifications": "- Body: Maple\n- Neck: Maple Through\n- Pickups: Hi-Gain Single-Coils\n- Outputs: Mono & Stereo\n- Includes: Hard Case",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Classic Vibe '60s Jazz Bass",
            "slug": "squier-classic-vibe-jazz-bass",
            "category": categories["bass-guitars"],
            "brand": "Squier",
            "condition": "new",
            "price": 449.99,
            "rating": 4.4,
            "description": "Affordable Squier Classic Vibe Jazz Bass with vintage styling and smooth playability.",
            "specifications": "- Body: Poplar\n- Neck: Maple\n- Fretboard: Indian Laurel\n- Pickups: Fender-Designed Alnico\n- Finish: 3-Color Sunburst",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "5-Piece Drum Kit",
            "slug": "pearl-export-drum-kit",
            "category": categories["drums"],
            "brand": "Pearl",
            "condition": "new",
            "price": 799.99,
            "rating": 4.6,
            "description": "Complete Pearl Export 5-piece drum kit. Includes hardware and cymbals. Perfect for beginners and professionals.",
            "specifications": '- Bass Drum: 22"\n- Toms: 10", 12"\n- Floor Tom: 16"\n- Snare: 14"\n- Includes: Hi-hat, Crash, Ride cymbals',
            "in_stock": True,
            "featured": True,
        },
        {
            "name": "Starclassic Maple Kit",
            "slug": "tama-starclassic-maple",
            "category": categories["drums"],
            "brand": "Tama",
            "condition": "used_excellent",
            "price": 2299.99,
            "rating": 4.8,
            "description": "Tama Starclassic Maple 4-piece shell pack with rich tone and pro hardware.",
            "specifications": '- Shells: Maple\n- Configuration: 22" BD, 10" & 12" Toms, 16" Floor\n- Finish: Satin Cherry Sunburst\n- Includes: Tom Mounts\n- Condition: Excellent',
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Breakbeats 4-Piece Kit",
            "slug": "ludwig-breakbeats-kit",
            "category": categories["drums"],
            "brand": "Ludwig",
            "condition": "used_good",
            "price": 499.99,
            "rating": 4.5,
            "description": "Questlove signature Ludwig Breakbeats compact kit ideal for small stages and practice.",
            "specifications": '- Configuration: 16" BD, 10" Rack, 13" Floor, 14" Snare\n- Shells: 7-ply Hardwood\n- Finish: Azure Sparkle\n- Includes: Bags\n- Compact footprint',
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "TD-27KV Electronic Kit",
            "slug": "roland-td27kv",
            "category": categories["drums"],
            "brand": "Roland",
            "condition": "new",
            "price": 2999.99,
            "rating": 4.9,
            "description": "Roland TD-27KV electronic drum kit with digital snare, hi-hat, and Bluetooth connectivity.",
            "specifications": "- Module: TD-27\n- Pads: Digital Snare/Hi-Hat, Mesh Toms\n- Cymbals: CY-14, CY-15R\n- Connectivity: USB Audio/MIDI\n- Includes: Rack",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Collector's Maple Snare",
            "slug": "dw-collectors-maple-snare",
            "category": categories["drums"],
            "brand": "DW",
            "condition": "used_excellent",
            "price": 649.99,
            "rating": 4.7,
            "description": "DW Collector's Series 14x6.5 maple snare with chrome hardware and crisp projection.",
            "specifications": "- Shell: North American Maple\n- Size: 14x6.5\n- Hoops: True-Hoop\n- Throw-Off: MAG\n- Finish: Satin Oil",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Headliner Cajon",
            "slug": "meinl-headliner-cajon",
            "category": categories["drums"],
            "brand": "Meinl",
            "condition": "new",
            "price": 129.99,
            "rating": 4.3,
            "description": "Meinl Headliner series cajon with adjustable snare wires for acoustic sessions.",
            "specifications": '- Material: Baltic Birch\n- Snare System: Adjustable\n- Dimensions: 11.75" x 19.75"\n- Finish: Espresso Burst\n- Includes: Allen key',
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Digital Piano",
            "slug": "yamaha-p45",
            "category": categories["keyboards"],
            "brand": "Yamaha",
            "condition": "new",
            "price": 549.99,
            "rating": 4.4,
            "description": "Yamaha P-45 88-key weighted digital piano. Realistic feel and sound, perfect for home practice.",
            "specifications": "- Keys: 88 weighted\n- Voices: 10\n- Polyphony: 64-note\n- Built-in speakers\n- USB connectivity",
            "in_stock": True,
            "featured": True,
        },
        {
            "name": "Synthesizer",
            "slug": "korg-minilogue",
            "category": categories["keyboards"],
            "brand": "Korg",
            "condition": "used_excellent",
            "price": 499.99,
            "rating": 4.3,
            "description": "Korg Minilogue analog synthesizer with 4-voice polyphony. Great for electronic music production.",
            "specifications": "- Voices: 4\n- Keys: 37 slim keys\n- Oscillators: 2 per voice\n- Built-in sequencer\n- Multiple effects",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "FP-30X Digital Piano",
            "slug": "roland-fp30x",
            "category": categories["keyboards"],
            "brand": "Roland",
            "condition": "new",
            "price": 799.99,
            "rating": 4.6,
            "description": "Roland FP-30X portable digital piano with PHA-4 action and Bluetooth audio/MIDI.",
            "specifications": "- Keys: 88 PHA-4\n- Polyphony: 256\n- Voices: SuperNATURAL Piano\n- Connectivity: Bluetooth, USB\n- Speakers: 11W x2",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Stage 3 Compact",
            "slug": "nord-stage-3-compact",
            "category": categories["keyboards"],
            "brand": "Nord",
            "condition": "used_excellent",
            "price": 3599.99,
            "rating": 4.9,
            "description": "Nord Stage 3 Compact with 73 semi-weighted waterfall keys and triple sound engines.",
            "specifications": "- Keys: 73 Waterfall\n- Engines: Piano, Organ, Synth\n- Effects: Comprehensive suite\n- Memory: 2GB Piano\n- Includes: Soft Case",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "PX-S1100 Smart Piano",
            "slug": "casio-pxs1100",
            "category": categories["keyboards"],
            "brand": "Casio",
            "condition": "new",
            "price": 649.99,
            "rating": 4.4,
            "description": "Slim Casio Privia PX-S1100 with Smart Scaled hammer action and Bluetooth audio.",
            "specifications": "- Keys: 88 Smart Scaled\n- Voices: 18\n- Polyphony: 192\n- Connectivity: Bluetooth, USB\n- Includes: Wireless Adapter",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Subsequent 37 Analog Synth",
            "slug": "moog-subsequent-37",
            "category": categories["keyboards"],
            "brand": "Moog",
            "condition": "used_good",
            "price": 1499.99,
            "rating": 4.7,
            "description": "Moog Subsequent 37 with dual ladder filters, paraphony, and rich analog modulation.",
            "specifications": "- Keys: 37\n- Oscillators: 2 + Sub\n- Modes: Monophonic/Paraphonic\n- Modulation: Dual LFO\n- Includes: Gig Bag",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Alto Saxophone",
            "slug": "yamaha-yas280",
            "category": categories["wind-instruments"],
            "brand": "Yamaha",
            "condition": "new",
            "price": 1999.99,
            "rating": 4.8,
            "description": "Yamaha YAS-280 student alto saxophone. Excellent tone quality and easy playability.",
            "specifications": "- Key: Eb\n- Finish: Gold lacquer\n- Includes: Hard case, mouthpiece, reeds\n- Perfect for students",
            "in_stock": True,
            "featured": True,
        },
        {
            "name": "Stradivarius Bb Trumpet",
            "slug": "bach-180s37-trumpet",
            "category": categories["wind-instruments"],
            "brand": "Bach",
            "condition": "used_excellent",
            "price": 2799.99,
            "rating": 4.9,
            "description": "Bach 180S37 Stradivarius trumpet with silver-plated finish and vibrant projection.",
            "specifications": '- Key: Bb\n- Bore: .459"\n- Bell: 37 Yellow Brass\n- Finish: Silver Plate\n- Includes: Case & Mouthpiece',
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "R13 Professional Clarinet",
            "slug": "buffet-crampon-r13",
            "category": categories["wind-instruments"],
            "brand": "Buffet Crampon",
            "condition": "used_good",
            "price": 2299.99,
            "rating": 4.7,
            "description": "Handcrafted Buffet R13 clarinet made from grenadilla wood for rich orchestral tone.",
            "specifications": "- Key: Bb\n- Body: Grenadilla\n- Keywork: Nickel Silver\n- Pads: Cork\n- Includes: Double Case",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "3SB Flute",
            "slug": "gemeinhardt-3sb-flute",
            "category": categories["wind-instruments"],
            "brand": "Gemeinhardt",
            "condition": "new",
            "price": 899.99,
            "rating": 4.5,
            "description": "Gemeinhardt 3SB open-hole flute with solid silver headjoint and B footjoint.",
            "specifications": "- Key: C\n- Head: Solid Silver\n- Body: Silver-Plated\n- Foot: B Foot\n- Includes: Case & Cover",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "88H Trombone",
            "slug": "conn-88h-trombone",
            "category": categories["wind-instruments"],
            "brand": "Conn",
            "condition": "used_good",
            "price": 1899.99,
            "rating": 4.6,
            "description": "Conn 88H tenor trombone with F-attachment, ideal for symphonic and studio work.",
            "specifications": '- Key: Bb/F\n- Bore: .547"\n- Bell: 8.5" Rose Brass\n- Finish: Lacquer\n- Includes: Hard Case',
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "62 Professional Tenor Sax",
            "slug": "yamaha-yts62",
            "category": categories["wind-instruments"],
            "brand": "Yamaha",
            "condition": "used_excellent",
            "price": 3199.99,
            "rating": 4.8,
            "description": "Yamaha YTS-62 professional tenor saxophone known for balanced response and projection.",
            "specifications": "- Key: Bb\n- Finish: Gold Lacquer\n- Neck: 62 Style\n- Pads: Leather with Plastic Resonators\n- Includes: Case",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Acoustic Dreadnought",
            "slug": "martin-d28",
            "category": categories["guitars"],
            "brand": "Martin",
            "condition": "used_excellent",
            "price": 2799.99,
            "rating": 4.9,
            "description": "Martin D-28 acoustic guitar with solid spruce top and rosewood back and sides. Rich, full sound.",
            "specifications": '- Top: Solid Spruce\n- Back/Sides: Rosewood\n- Neck: Mahogany\n- Scale: 25.4"\n- Includes: Hard case',
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Student Violin",
            "slug": "yamaha-v3ska",
            "category": categories["string-instruments"],
            "brand": "Yamaha",
            "condition": "new",
            "price": 329.99,
            "rating": 4.2,
            "description": "Yamaha V3 SKA 4/4 student violin outfit. Great quality for beginners.",
            "specifications": "- Size: 4/4\n- Top: Spruce\n- Back/Sides: Maple\n- Includes: Case, bow, rosin",
            "in_stock": True,
            "featured": False,
        },
        {
            "name": "Classical Guitar",
            "slug": "cordoba-c5",
            "category": categories["guitars"],
            "brand": "Cordoba",
            "condition": "new",
            "price": 399.99,
            "rating": 4.6,
            "description": "Cordoba C5 classical guitar with cedar top and mahogany back and sides. Warm, mellow tone.",
            "specifications": "- Top: Canadian Cedar\n- Back/Sides: Mahogany\n- Neck: Mahogany\n- Fretboard: Rosewood\n- Nylon strings",
            "in_stock": True,
            "featured": False,
        },
    ]

    for inst_data in instruments_data:
        instrument, created = Instrument.objects.update_or_create(slug=inst_data["slug"], defaults=inst_data)
        print(f"{'Created' if created else 'Updated'} instrument: {instrument.brand} {instrument.name}")

    print("\nDatabase population complete!")
    print(f"Total categories: {Category.objects.count()}")
    print(f"Total instruments: {Instrument.objects.count()}")
    print("\nYou can now view the store at: http://127.0.0.1:8000/")
    print("Admin panel at: http://127.0.0.1:8000/admin/")


if __name__ == "__main__":
    populate_database()
